export declare function dynImport(path: any): Promise<any>;
export { TtestClass } from './TtestClass';
import * as events from "./lib/events";
import * as tools from "./lib/tools";
import * as dao from "./lib/dao";
import * as cluster from "./lib/cluster";
import * as rest from "./lib/rest";
import * as exceptions from "./lib/exceptions";
import * as services from "./lib/services";
export { Tworker } from './lib/Tworker';
export { Tapplication } from './lib/Tapplication';
export { services, events, tools, dao, cluster, rest, exceptions };
